name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setupup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        working-directory: ./java/src
        run: javac ./lab6/exceptions/NoTranslationException.java ./lab6/dictionary/TranslateDictionaryModel.java ./lab6/dictionary/TranslateDictionaryModel.java ./lab6/dictionary/TranslateDictionaryController.java ./lab6/scanner/InputScanner.java ./lab6/menu/MenuStates.java ./lab6/menu/MenuView.java ./lab6/menu/MenuModel.java ./lab6/menu/MenuController.java ./lab6/Main.java

      - name: Test
        working-directory: ./java
        run: |
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./src/lab6/dictionary/TranslateDictionaryModel.java ./src/lab6/tests/TranslateDictionaryTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab6.tests.TranslateDictionaryTests          